### ISSUE TITLE
ValueError: Mat 4 mopt wrong format, byteswapping problem  

### ISSUE THREAD

**Issue by hopesala** [jianzhangcs/SCI3D#2]
I download the net_100.pth from google drive, and run the test.py , the command is bellow, (slightly different from the readme[--result ./results/simulation/ --model_dir ./checkpoint ])
but it got error: Mat 4 mopt wrong format, byteswapping problem?
is the  net_100.pth file format right, what's wrong with the code or the .pth file, I am confused, please help, thanks very much

(base) cao@cao-OMEN-by-HP-Desktop-PC-880-p0xx:/media/cao/CAO/Doctor/SCI3D-main$ python test.py --test_dir ./simulation_dataset --result ./results/simulation/ --model_dir ./checkpoint --layer_num 10 --temporal_patch 3 --n_channels 1
Traceback (most recent call last):
  File "test.py", line 111, in <module>
    test_simulation()
  File "test.py", line 64, in test_simulation
    Training_data = sio.loadmat(os.path.join(args.test_dir, test_list[i]))
  File "/home/cao/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 226, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/home/cao/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/_mio4.py", line 399, in get_variables
    hdr, next_position = self.read_var_header()
  File "/home/cao/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/_mio4.py", line 355, in read_var_header
    hdr = self._matrix_reader.read_header()
  File "/home/cao/anaconda3/lib/python3.8/site-packages/scipy/io/matlab/_mio4.py", line 117, in read_header
    raise ValueError('Mat 4 mopt wrong format, byteswapping problem?')
ValueError: Mat 4 mopt wrong format, byteswapping problem?

**Comment by hopesala** [comment]
@jianzhangcs @MC-E

**Comment by hopesala** [comment]
I found the reason, the mat file is copied from MacOS, ._aerial.mat* is hidden , which caused this problem


ls
aerial.mat  crash.mat  drop.mat  kobe.mat  runner.mat  traffic.mat
(base) cao@cao-OMEN-by-HP-Desktop-PC-880-p0xx:/media/cao/CAO/Doctor/SCI3D-main/simulation_dataset$ ll
total 35608
drwxrwxrwx 1 cao cao     4096  3月 21 10:20 ./
drwxrwxrwx 1 cao cao     8192  3月 22 00:09 ../
-rwxrwxrwx 2 cao cao     4096  3月 21 10:11 ._aerial.mat*
-rwxrwxrwx 1 cao cao  5775208  9月 16  2021 aerial.mat*
-rwxrwxrwx 2 cao cao     4096  3月 21 10:11 ._crash.mat*
-rwxrwxrwx 1 cao cao  5251031  9月 16  2021 crash.mat*
-rwxrwxrwx 2 cao cao     4096  3月 21 10:11 ._drop.mat*
-rwxrwxrwx 1 cao cao  1735166  9月 16  2021 drop.mat*
-rwxrwxrwx 2 cao cao     4096  3月 21 10:11 ._kobe.mat*
-rwxrwxrwx 1 cao cao 17640504  9月 16  2021 kobe.mat*
-rwxrwxrwx 2 cao cao     4096  3月 21 10:11 ._runner.mat*
-rwxrwxrwx 1 cao cao  2355109  9月 16  2021 runner.mat*
-rwxrwxrwx 2 cao cao     4096  3月 21 10:11 ._traffic.mat*
-rwxrwxrwx 1 cao cao  3663489  9月 16  2021 traffic.mat*
(base) cao@cao-OMEN-by-HP-Desktop-PC-880-p0xx:/media/cao/CAO/Doctor/SCI3D-main/simulation_dataset$ rm -rf ._*.mat
(base) cao@cao-OMEN-by-HP-Desktop-PC-880-p0xx:/media/cao/CAO/Doctor/SCI3D-main/simulation_dataset$ ll
total 35584
drwxrwxrwx 1 cao cao     4096  3月 22 00:10 ./
drwxrwxrwx 1 cao cao     8192  3月 22 00:09 ../
-rwxrwxrwx 1 cao cao  5775208  9月 16  2021 aerial.mat*
-rwxrwxrwx 1 cao cao  5251031  9月 16  2021 crash.mat*
-rwxrwxrwx 1 cao cao  1735166  9月 16  2021 drop.mat*
-rwxrwxrwx 1 cao cao 17640504  9月 16  2021 kobe.mat*
-rwxrwxrwx 1 cao cao  2355109  9月 16  2021 runner.mat*
-rwxrwxrwx 1 cao cao  3663489  9月 16  2021 traffic.mat*
